.github/workflows/ci.yml
.github/workflows/enable-docker-experimental.sh
.github/workflows/publish.yml

Note:
The choice to store docker containers on docker.pkg.github.com is intentional as we need to experiment. Once we are happy with results, we should be moving the container storage to the mainstream docker hub.

SAAS-177 setup grafana repo

---

public/app/features/integrated-alerting/components/AlertRules/AlertRules.types.ts
public/app/features/integrated-alerting/components/AlertRules/AlertRules.utils.test.ts
public/app/features/integrated-alerting/components/AlertRules/AlertRules.utils.ts
public/app/features/integrated-alerting/components/AlertRules/AlertRulesTable/AlertRulesTable.test.tsx
public/app/features/integrated-alerting/components/AlertRules/AlertRulesTable/AlertRulesTable.tsx
public/app/features/integrated-alerting/components/AlertRules/__mocks__/alertRulesStubs.ts

What this PR does / why we need it: Show an alert's parsed expression instead of the rule's YAML.
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7433
Added `expr` (coming now from the API) in both `AlertRule` and `AlertRulesListResponseRule`. Then, just changed the table to show `alertRule.expr` in the `<pre>` block.

PMM-7433 Show "expr" in alert rule details

---

public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.service.test.ts

What this PR does / why we need it: `NotificationChannelService` was broken due to wrong mocking after using api helper.

fix: notification service mock

---

public/app/features/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.test.tsx
public/app/features/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx

What this PR does / why we need it: Allows editing an alert rule's name. While on edition, the template used is also shown, even though it's blocked.
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7260
- Always show name field (was hidden while on edition);
- When on edition, just `disable` the template `Select` instead of hiding it.

PMM-7260: edit rule name

---

public/app/features/backup/components/StorageLocations/WarningBlock/WarningBlock.styles.ts
public/app/features/backup/components/StorageLocations/WarningBlock/WarningBlock.test.tsx
public/app/features/backup/components/StorageLocations/WarningBlock/WarningBlock.tsx
public/app/features/backup/components/StorageLocations/WarningBlock/WarningBlock.types.ts
public/app/features/backup/components/StorageLocations/WarningBlock/index.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.types.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplateActions/AlertRuleTemplateActions.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/EditAlertRuleTemplateModal/EditAlertRuleTemplateModal.constants.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/EditAlertRuleTemplateModal/EditAlertRuleTemplateModal.messages.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/EditAlertRuleTemplateModal/EditAlertRuleTemplateModal.styles.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/EditAlertRuleTemplateModal/EditAlertRuleTemplateModal.test.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/EditAlertRuleTemplateModal/EditAlertRuleTemplateModal.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/EditAlertRuleTemplateModal/EditAlertRuleTemplateModal.types.ts

What this PR does / why we need it: The API now requires the name of a given template to be sent when editing. Also, the name of the template is on the modal's title and there's a warning stating that the template's name can't be changed.
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7375
- Add template name modal's title;
- Add warning above buttons;
- Send name along on the API request.

PMM-7375: Send tempate name while editing

---

public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.constants.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.service.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.test.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.types.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/__mocks__/AlertRuleTemplate.service.ts
public/app/features/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx

What this PR does / why we need it: Adds pagination to Alert Rule Templates
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7510
The logic is the same as in Alert rules, no more, no less.

PMM-7510: add pagination to rule templates

---

public/app/percona/backup/components/StorageLocations/StorageLocations.tsx

https://github.com/Percona-Lab/pmm-submodules/pull/1634
What this PR does / why we need it: only closes modal when API successfully returns
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7774

PMM-7774: do not close storage location modal on error

---

public/app/core/components/sidemenu/TopSection.tsx
public/app/percona/backup/components/StorageLocations/AddStorageLocationModal/AddStorageLocationModal.test.tsx
public/app/percona/backup/components/StorageLocations/AddStorageLocationModal/AddStorageLocationModal.tsx
public/app/percona/backup/components/StorageLocations/AddStorageLocationModal/AddStorageLocationModal.types.ts
public/app/percona/backup/components/StorageLocations/StorageLocations.tsx
public/app/percona/shared/helpers/permissions.ts

https://github.com/Percona-Lab/pmm-submodules/pull/1648
What this PR does / why we need it: fixes the permission problem for non-Server Admins on Grafana
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7823
- creates `isPmmAdmin` function, that checks if a user is either a Server Admin or an Org Admin;
- removes admin check from "Test" button on AddStorageLocationModal, as that's redundant.

PMM-7823: permissions

---

public/app/percona/dbaas/components/DBCluster/DBCluster.hooks.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.tsx

**What this PR does / why we need it**: Fixes DB Cluster tab in DBaaS not showing loading by default. This is a simple fix but the underlying issue is much bigger and is related to the `TabbedContent` component. Please see: https://jira.percona.com/browse/PMM-7930
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7884

PMM-7884 Fix DB cluster tab loading

---

public/app/percona/backup/components/BackupInventory/BackupInventoryActions/BackupInventoryActions.tsx
public/app/percona/backup/components/DBIcon/DBIcon.styles.ts
public/app/percona/backup/components/DBIcon/DBIcon.tsx
public/app/percona/backup/components/DBIcon/DBIcon.types.ts

What this PR does / why we need it: some actions for backup artifacts should be disabled depending on their status. In this case in particular, a backup can't be restored unless it has successfully finished.
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7953
- Add `disabled` prop to `DBIcon`;
- Use Grafana theme's `colors.textFaint` for disabled effect, remove pointer-events and change cursor;

PMM-7953: disabled backup actions

---

public/app/percona/dbaas/DBaaS.tsx
public/app/percona/dbaas/components/DBCluster/PSMDB.service.ts
public/app/percona/dbaas/components/DBCluster/XtraDB.service.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.utils.test.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.utils.ts

**What this PR does / why we need it**: Hide DB cluster list API error, if request fails we don't want to show the error. Rather the related cluster will disappear from the list and the user can see on k8s tab that the k8s that it's trying to access is unavailable
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7528

PMM-7528 Hide DB cluster list error

---

public/app/percona/backup/components/BackupInventory/BackupInventory.tsx
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.messages.ts
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.styles.ts
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.test.tsx
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.tsx
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.types.ts

What this PR does / why we need it: when there's no serviceId or serviceName (because it was deleted) for a given backup, block the "restore" button in the modal and show an error message.
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-8153

PMM-8153: block restore when there is no service

---

packages/grafana-ui/src/components/Portal/Portal.tsx
public/app/percona/dbaas/DBaaS.messages.ts
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/AddDBClusterModal.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/AddDBClusterModal.types.ts
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.types.ts
public/app/percona/dbaas/components/DBCluster/DBClusterParameters/DBClusterParameters.test.tsx
public/app/percona/dbaas/components/DBCluster/DBClusterParameters/DBClusterParameters.tsx
public/app/percona/dbaas/components/DBCluster/PSMDB.service.ts
public/app/percona/dbaas/components/DBCluster/XtraDB.service.ts
public/app/percona/dbaas/components/DBCluster/__mocks__/dbClustersStubs.ts
public/app/percona/dbaas/components/Switch/Switch.styles.ts
public/app/percona/dbaas/components/Switch/Switch.test.tsx
public/app/percona/dbaas/components/Switch/Switch.tsx
public/app/percona/dbaas/components/Switch/Switch.types.ts

**What this PR does / why we need it**: 
- Adds `Switch` to DB Cluster creation page to enable external access for the DB cluster (exposes the cluster to the world)
- New `Switch` component was added that allows a tooltip, the idea is to contribute this Switch to core
- Found a bug in grafana: tooltips have lower z-index than the modal, which means tooltips don't show in the modal because they are hidden underneath. I will later open a PR on grafana to fix it on their side
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7659

PMM-7659 Add external access to DB cluster

---

pkg/api/index.go

What this PR does / why we need it:
fix typo in grafana menu Utilisation -> Utilization
Which issue(s) this PR fixes: 
https://jira.percona.com/browse/PMM-8265

PMM-8265 fix typo in Utilisation

---

pkg/api/http_server.go
pkg/api/login_oauth.go
pkg/api/percona_api.go
pkg/api/user_token.go

This endpoint will be needed by pmm-managed when disconnecting from Portal.
Format:
`GET /percona-api/user/oauth-token`
Response:
```
{
access_token: <token>,
refresh_token: <token>,
expiry: <expiry>,
token_type: <type, e.g. "Bearer">
}
```

Create endpoint to retrieve OAuth token

---

public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.service.tsx
public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.types.ts

After API changes (https://github.com/percona/pmm/pull/799), we need to change the type of stats_collections in the FE part from string to string[];
https://jira.percona.com/browse/PMM-9253

PMM-9193-add-collectios-metrics-fields-to-mongo: fix placeholders

---

.github/workflows/ui-tests.yml

Run ui-tests take an average of 26-28 minutes and a 30-minutes timeout is not enough.
Fixes #

PMM-7 increase timeout for ui-tests

---

public/app/percona/add-instance/components/AddInstance/AddInstance.messages.ts
public/app/percona/add-instance/components/AddInstance/AddInstance.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/ExternalServiceConnectionDetails/ExternalServiceConnectionDetails.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.test.tsx

On the Grafana dashboard to add a new instance in Inventory, the AWS entry is misleading. It highlights that only MySQL is supported for RDS or Aurora.
Moreover, current documentation acknowledges the fact that Postgres is supported on AWS RDS.
https://jira.percona.com/browse/PMM-9144

PMM-9144: Remove mySQL from "AWS RDS MySQL or Aurora MySQL" title

---

public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.tsx

**What this PR does / why we need it**: Stops scheduling more resources requests after the component unmounts.
Tried to cancel the request but even if canceled the next one gets scheduled, in order to prevent that we need to store if the component is mounted or not. (not using a ref here because the value needs to be set to true every time the component renders, just using a standard reference)
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8535

PMM-8535 Stop resources request

---

public/app/percona/check/components/FailedChecksTab/FailedChecksTab.messages.ts
public/app/percona/check/components/FailedChecksTab/FailedChecksTab.tsx

**What this PR does / why we need it**: This PR removes 10 seconds delay before showing a pop-up message when the user runs DB checks. Also, the message is adjusted according to the changes on a BE
https://jira.percona.com/browse/PMM-9485
Fixes #
**FB**: https://github.com/Percona-Lab/pmm-submodules/pull/2282

PMM-9485 change run db checks popup message

---

public/app/percona/settings/Settings.service.ts

**What this PR does / why we need it:**
**Which issue(s) this PR fixes:**
https://jira.percona.com/browse/PMM-10587

PMM-10587: Set default value for telemetry_summaries endpoint to not break UI if it's empty

---

public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/AddDBClusterModal.test.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/AddDBClusterModal.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/AddDBClusterModal.types.ts
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/AddDBClusterModal.utils.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.test.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.tsx
public/app/percona/dbaas/components/Kubernetes/KubernetesInventory.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusRow/OperatorStatusRow.styles.ts
public/app/percona/dbaas/components/Kubernetes/OperatorStatusRow/OperatorStatusRow.test.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusRow/OperatorStatusRow.tsx
public/app/percona/shared/core/reducers.ts
public/app/percona/shared/core/selectors.ts

https://jira.percona.com/browse/PMM-10349
To deploy the initial DB Cluster, the user who just configured K8s needs to know about the second tab in UI to test the deployment.  It will be better to give them an easy solution to deploy into just added k8s Cluster 
[Запись встречи 17.08.2022 17-06-45 - запись.webm](https://user-images.githubusercontent.com/90199600/185141991-e2682077-da4d-4300-b2c6-29b61e8a7f2a.webm)

PMM-10349 DBaaS easy access to deploy button

---

devenv/docker/ha-test-unified-alerting/grafana/provisioning/dashboards/mysql/overview.json
devenv/docker/ha_test/grafana/provisioning/dashboards/mysql/overview.json
public/app/core/components/Footer/Footer.tsx
public/app/features/dashboard/components/ShareModal/ShareLink.tsx
public/app/percona/add-instance/components/Discovery/components/DiscoveryDocs/DiscoveryDocs.constants.ts
public/app/percona/backup/components/AddBackupPage/AddBackupPage.messages.ts
public/app/percona/rbac/AccessRoles/AccessRoles.tsx
public/app/percona/settings/Settings.messages.ts
public/app/percona/settings/components/Communication/Communication.messages.ts
public/app/percona/settings/components/Platform/Connected/ModalBody/ModalBody.constants.ts
public/app/percona/shared/components/PerconaBootstrapper/PerconaBootstrapper.tsx
public/app/percona/shared/helpers/api.ts
public/app/percona/tour/steps/product/product.steps.tsx

Updates docs link to use shortener.
PMM-12310
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3352
**Relevant PRs**:
- https://github.com/percona/grafana-dashboards/pull/1533

PMM-12310 Use shortener for docs links

---

public/app/percona/shared/helpers/validators.test.tsx
public/app/percona/shared/helpers/validators.ts

Lessens restrictions on custom labels to include uppercase, dashes, underscores, etc.
PMM-12382
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3354
Prometheus Data Model - https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
In short keys must match following regex `[a-zA-Z_][a-zA-Z0-9_]*`, value can contain any unicode characters.  In our case spaces (used to separe labels) and colons (used as key/value separator) are not permitted in value.

PMM-12382 Match custom labels based on prometheus model

---

go.mod
go.sum

This should address the [CVE](https://github.com/prometheus/exporter-toolkit/security/advisories/GHSA-7rg2-cxvp-9p7p) reported for v0.7.1.
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3409

PMM-7 bump up exporter-toolkit to v0.7.2

---

packages/grafana-schema/src/raw/composable/annotationslist/panelcfg/x/AnnotationsListPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/barchart/panelcfg/x/BarChartPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/bargauge/panelcfg/x/BarGaugePanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/candlestick/panelcfg/x/CandlestickPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/canvas/panelcfg/x/CanvasPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/cloudwatch/dataquery/x/CloudWatchDataQuery_types.gen.ts
packages/grafana-schema/src/raw/composable/dashboardlist/panelcfg/x/DashboardListPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/datagrid/panelcfg/x/DatagridPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/debug/panelcfg/x/DebugPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/elasticsearch/dataquery/x/ElasticsearchDataQuery_types.gen.ts
packages/grafana-schema/src/raw/composable/gauge/panelcfg/x/GaugePanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/geomap/panelcfg/x/GeomapPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/heatmap/panelcfg/x/HeatmapPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/histogram/panelcfg/x/HistogramPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/logs/panelcfg/x/LogsPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/loki/dataquery/x/LokiDataQuery_types.gen.ts
packages/grafana-schema/src/raw/composable/news/panelcfg/x/NewsPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/nodegraph/panelcfg/x/NodeGraphPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/piechart/panelcfg/x/PieChartPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/stat/panelcfg/x/StatPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/statetimeline/panelcfg/x/StateTimelinePanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/statushistory/panelcfg/x/StatusHistoryPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/table/panelcfg/x/TablePanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/text/panelcfg/x/TextPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/timeseries/panelcfg/x/TimeSeriesPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/trend/panelcfg/x/TrendPanelCfg_types.gen.ts
packages/grafana-schema/src/raw/composable/xychart/panelcfg/x/XYChartPanelCfg_types.gen.ts

Ran `make gen-cue` to regenerate files. Should get rid of **golangci-lint / lint-go** we've been seeing.

PMM-7 Generate plugin versions

---

docker-compose.yml
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/ExternalServiceConnectionDetails/ExternalServiceConnectionDetails.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/HAProxyConnectionDetails/HAProxyConnectionDetails.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/NodesAgents/NodesAgents.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/NodesAgents/NodesAgents.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/NodesAgents/NodesAgents.types.ts
public/app/percona/shared/core/reducers/nodes/nodes.utils.ts

It doesn't override address when node or agent is changed.
dropped node/agent selection for HAProxy and External exporter as it doesn't have effect.
Fixes #

PMM-13428 Fix add remote instance issues.

---

public/app/percona/shared/components/PerconaBootstrapper/PerconaUpdateVersion/PerconaUpdateVersion.constants.ts
public/app/percona/shared/components/PerconaBootstrapper/PerconaUpdateVersion/PerconaUpdateVersion.styles.ts
public/app/percona/shared/components/PerconaBootstrapper/PerconaUpdateVersion/PerconaUpdateVersion.tsx
public/app/percona/shared/core/reducers/updates/updates.utils.ts

https://perconadev.atlassian.net/browse/PMM-13472

PMM-13472: Update Popup - Wording improvements

---

public/app/plugins/panel/pmm-check/components/Failed/Failed.test.tsx
public/app/plugins/panel/pmm-check/components/Failed/Failed.tsx

[PMM-13826](https://perconadev.atlassian.net/browse/PMM-13826)
https://github.com/Percona-Lab/pmm-submodules/pull/3867
[PMM-13826]: https://perconadev.atlassian.net/browse/PMM-13826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PMM-13826 handled role check to show editor users failed advisors number

---

.github/workflows/detect-breaking-changes-build-skip.yml
.github/workflows/detect-breaking-changes-build.yml
.github/workflows/ui-tests.yml
public/app/percona/shared/components/PerconaBootstrapper/PerconaBootstrapper.tsx
public/app/percona/shared/components/PerconaBootstrapper/PerconaNewVersion/PerconaNewVersion.constants.ts
public/app/percona/shared/components/PerconaBootstrapper/PerconaNewVersion/PerconaNewVersion.messages.ts
public/app/percona/shared/components/PerconaBootstrapper/PerconaNewVersion/PerconaNewVersion.styles.ts
public/app/percona/shared/components/PerconaBootstrapper/PerconaNewVersion/PerconaNewVersion.tsx
public/app/percona/shared/components/PerconaBootstrapper/PerconaNewVersion/PerconaNewVersion.types.ts
public/app/percona/shared/components/PerconaBootstrapper/PerconaNewVersion/index.ts

https://perconadev.atlassian.net/browse/PMM-13746
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3881

PMM-13746 issue a popup to advise users to migrate to PMM v3

---

public/app/percona/shared/core/reducers/updates/updates.ts

https://perconadev.atlassian.net/browse/PMM-13453
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3870

PMM-13453 changed the force flag for /server/updates to false

---

public/app/core/components/Footer/Footer.tsx
public/app/percona/pmm-dump/components/ExportDataset/ExportDataset.tsx
public/app/percona/shared/components/PerconaBootstrapper/PerconaNavigation/PerconaNavigation.tsx
public/app/routes/routes.tsx

[PMM-13596](https://perconadev.atlassian.net/browse/PMM-13596)
[PMM-13596]: https://perconadev.atlassian.net/browse/PMM-13596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
FB:https://github.com/Percona-Lab/pmm-submodules/pull/3879

PMM-13596 Add access control for logs and dump
