public/app/core/components/Branding/Branding.tsx
public/app/core/components/Footer/Footer.tsx
public/app/core/components/Footer/LoginFooter.tsx
public/app/core/components/Login/LoginLayout.tsx
public/app/core/components/sidemenu/BottomNavLinks.tsx
public/img/percona-logo.svg
public/sass/components/_footer.scss
public/sass/components/_sidemenu.scss
public/views/index-template.html

To test:
1/ generate a token (https://github.com/settings/tokens) to be able to use the docker registry at docker.pkg.github.com
2/ login to the github registry `docker login docker.pkg.github.com`
3/ pull the image `docker pull docker.pkg.github.com/percona-platform/grafana/grafana:dev`
4/ run `docker run --name grafana7 --rm -p 80:3000 docker.pkg.github.com/percona-platform/grafana/grafana:dev`
5/ goto http://localhost in your browser & test it )

PMM-5868 pmm branding in v7

---

public/app/features/dashboard/components/ShareModal/ShareLink.tsx

PMM-6598 change panel sharing text

---

public/app/features/integrated-alerting/IntegratedAlerting.messages.ts
public/app/features/integrated-alerting/IntegratedAlerting.styles.ts
public/app/features/integrated-alerting/IntegratedAlerting.types.ts
public/app/features/integrated-alerting/IntegratedAlertingPage.test.tsx
public/app/features/integrated-alerting/IntegratedAlertingPage.tsx

**What this PR does / why we need it**: Adds Integrated Alerting Tab Bar
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-6977

PMM-6977 Add IA tab bar

---

pkg/api/index.go
public/app/core/components/sidemenu/TopSection.tsx
public/app/core/components/sidemenu/TopSection.utils.test.ts
public/app/core/components/sidemenu/TopSection.utils.ts
public/app/features/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/AddNotificationChannelModal.tsx
public/app/features/integrated-alerting/components/NotificationChannel/DeleteNotificationChannelModal/DeleteNotificationChannelsModal.messages.ts
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.service.ts

**What this PR does / why we need it**: Adds IA toggle and feature flag
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-6956

PMM-6956 IA feature flag

---

pkg/api/index.go
public/app/core/__mocks__/app_events.ts
public/app/core/components/sidemenu/TopSection.tsx
public/app/core/components/sidemenu/TopSection.utils.test.ts
public/app/core/components/sidemenu/TopSection.utils.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/AddAlertRuleTemplateModal/AddAlertRuleTemplateModal.test.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/EditAlertRuleTemplateModal/EditAlertRuleTemplateModal.test.tsx
public/app/features/integrated-alerting/components/DeleteModal/DeleteModal.messages.ts
public/app/features/integrated-alerting/components/DeleteModal/DeleteModal.styles.ts
public/app/features/integrated-alerting/components/DeleteModal/DeleteModal.test.tsx
public/app/features/integrated-alerting/components/DeleteModal/DeleteModal.tsx
public/app/features/integrated-alerting/components/DeleteModal/DeleteModal.types.ts
public/app/features/integrated-alerting/components/DeleteModal/index.ts
public/app/features/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/AddNotificationChannelModal.test.tsx
public/app/features/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/AddNotificationChannelModal.tsx
public/app/features/integrated-alerting/components/NotificationChannel/DeleteNotificationChannelModal/DeleteNotificationChannelModal.test.tsx
public/app/features/integrated-alerting/components/NotificationChannel/DeleteNotificationChannelModal/DeleteNotificationChannelModal.tsx
public/app/features/integrated-alerting/components/NotificationChannel/DeleteNotificationChannelModal/DeleteNotificationChannelModal.types.ts
public/app/features/integrated-alerting/components/NotificationChannel/DeleteNotificationChannelModal/DeleteNotificationChannelsModal.messages.ts
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.service.ts
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.test.tsx
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.tsx
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.types.ts
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannelActions/NotificationChannelActions.styles.ts
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannelActions/NotificationChannelActions.test.tsx
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannelActions/NotificationChannelActions.tsx
public/app/features/integrated-alerting/components/NotificationChannel/__mocks__/NotificationChannel.service.ts
public/app/features/integrated-alerting/components/NotificationChannel/__mocks__/notificationChannelStubs.ts

**What this PR does / why we need it**: Delete notification channel
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-6963

PMM-6963 Notification channel delete

---

public/app/features/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/AddNotificationChannelModal.messages.ts
public/app/features/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/SlackFields/SlackFields.test.tsx
public/app/features/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/SlackFields/SlackFields.tsx

**What this PR does / why we need it**: Adds validation to slack channel name to not allow "#".
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7239

PMM-7239 Validate slack channel name

---

public/app/features/integrated-alerting/components/AlertRules/AlertRules.styles.ts
public/app/features/integrated-alerting/components/AlertRules/AlertRules.test.tsx
public/app/features/integrated-alerting/components/AlertRules/AlertRules.tsx
public/app/features/integrated-alerting/components/AlertRules/AlertRules.types.ts
public/app/features/integrated-alerting/components/AlertRules/AlertRules.utils.test.ts
public/app/features/integrated-alerting/components/AlertRules/AlertRulesActions/AlertRulesActions.test.tsx
public/app/features/integrated-alerting/components/AlertRules/AlertRulesActions/AlertRulesActions.tsx
public/app/features/integrated-alerting/components/AlertRules/AlertRulesTable/AlertRulesTable.styles.ts
public/app/features/integrated-alerting/components/AlertRules/AlertRulesTable/AlertRulesTable.test.tsx
public/app/features/integrated-alerting/components/AlertRules/AlertRulesTable/AlertRulesTable.tsx
public/app/features/integrated-alerting/components/AlertRules/__mocks__/alertRulesStubs.ts

**What this PR does / why we need it**: Adds alert rule detais
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7065

PMM-7065 Add alert rule details

---

public/app/features/integrated-alerting/components/Alerts/AlertsTable/AlertsTable.styles.ts
public/app/features/integrated-alerting/components/Alerts/AlertsTable/AlertsTable.tsx
public/app/features/integrated-alerting/components/Alerts/AlertsTable/AlertsTable.utils.test.ts
public/app/features/integrated-alerting/components/Alerts/AlertsTable/AlertsTable.utils.ts

**What this PR does / why we need it**: Adds colors to the severity in alerts list
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7082

PMM-7082 Add severity colors to alerts

---

public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.service.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.types.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplateActions/AlertRuleTemplateActions.styles.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplateActions/AlertRuleTemplateActions.test.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplateActions/AlertRuleTemplateActions.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplatesTable/AlertRuleTemplatesTable.types.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/DeleteRuleTemplateModal/DeleteRuleTemplateModal.messages.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/DeleteRuleTemplateModal/DeleteRuleTemplateModal.test.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/DeleteRuleTemplateModal/DeleteRuleTemplateModal.tsx
public/app/features/integrated-alerting/components/AlertRuleTemplate/DeleteRuleTemplateModal/DeleteRuleTemplateModal.types.ts
public/app/features/integrated-alerting/components/AlertRuleTemplate/__mocks__/AlertRuleTemplate.service.ts

**What this PR does / why we need it**: Delete alert rule template
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-6941

PMM-6941 Delete alert rule template

---

public/app/features/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx
public/app/features/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.utils.ts

**What this PR does / why we need it**: Doesn't require channels or filters to create alert rulte
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7282

PMM-7282 Create rule without channels and filters

---

public/app/core/components/Breadcrumb/Breadcrumb.styles.ts
public/app/core/components/Breadcrumb/Breadcrumb.test.tsx
public/app/core/components/Breadcrumb/Breadcrumb.tsx
public/app/core/components/Breadcrumb/Breadcrumb.types.ts
public/app/core/components/Breadcrumb/BreadcrumbSections.test.tsx
public/app/core/components/Breadcrumb/BreadcrumbSections.tsx
public/app/core/components/Breadcrumb/index.ts
public/app/features/integrated-alerting/IntegratedAlerting.constants.ts
public/app/features/integrated-alerting/IntegratedAlerting.types.ts
public/app/features/integrated-alerting/IntegratedAlertingPage.test.tsx
public/app/features/integrated-alerting/IntegratedAlertingPage.tsx
public/app/features/integrated-alerting/components/Alerts/AlertsActions/icons/Bell.tsx
public/app/features/integrated-alerting/components/Alerts/AlertsActions/icons/BellBarred.tsx
public/app/routes/routes.ts

https://github.com/Percona-Lab/pmm-submodules/pull/1467

PMM-6924 page breadcrumb component

---

pkg/api/api.go
pkg/api/apikey.go
pkg/api/user.go
pkg/models/apikey.go

https://github.com/Percona-Lab/pmm-submodules/pull/1479

PMM-6693 Endpoint to get current API Key

---

pkg/api/apikey.go

PMM-6693 Better error message.

---

public/app/features/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx
public/app/features/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/AddNotificationChannelModal.utils.test.ts
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.service.test.ts
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.service.ts
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.tsx
public/app/features/integrated-alerting/components/NotificationChannel/NotificationChannel.types.ts
public/app/features/integrated-alerting/components/NotificationChannel/__mocks__/NotificationChannel.service.ts

What this PR does / why we need it: Adds pagination to Notification Channels
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7511

PMM-7511: channels pagination

---

public/app/features/integrated-alerting/components/Table/Pagination/index.ts
public/app/features/integrated-alerting/components/Table/Table.tsx
public/app/features/integrated-alerting/components/Table/Table.utils.ts

This reverts commit 2a4e292fe89c18fe4bc8875dd2849595009fe324.

Revert "Fix bad PAGE_SIZES import (#93)"

---

public/app/percona/dbaas/components/DBCluster/DBCluster.constants.ts

**What this PR does / why we need it**: Fixes DBaaS  setting Link
**Which issue(s) this PR fixes**: PMM-7859
Fixes #

PMM-7859 fix settings link

---

public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterBasicOptions/DBClusterBasicOptions.hooks.ts
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterBasicOptions/DBClusterBasicOptions.utils.test.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.service.utils.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.types.ts
public/app/percona/dbaas/components/DBCluster/OptionContent/OptionContent.styles.ts
public/app/percona/dbaas/components/DBCluster/OptionContent/OptionContent.tsx
public/app/percona/dbaas/components/DBCluster/PSMDB.service.ts
public/app/percona/dbaas/components/DBCluster/XtraDB.service.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersions.hooks.test.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersions.hooks.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersions.utils.test.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersions.utils.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersions.utils.tsx
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersionsModal.constants.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersionsModal.messages.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersionsModal.styles.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersionsModal.test.tsx
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersionsModal.tsx
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersionsModal.types.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/__mocks__/ManageComponentsVersions.hooks.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/__mocks__/componentsVersionsStubs.ts
public/app/percona/shared/components/Form/FieldAdapters/FieldAdapters.tsx
public/app/percona/shared/components/Form/MultiCheckbox/MultiCheckboxField.tsx

**What this PR does / why we need it**: Adds default version to the modal to manage versions of the cluster components
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7576

PMM-7576 Default version

---

public/app/core/components/sidemenu/SideMenuDropDown.tsx
public/app/core/components/sidemenu/TopSection.tsx

Remove redundant fragment and avoid error due to bad key placement

Sidemenu: remove useless fragment

---

public/app/percona/backup/components/BackupInventory/BackupInventoryDetails/BackupInventoryDetails.styles.ts
public/app/percona/backup/components/BackupInventory/BackupInventoryDetails/BackupInventoryDetails.test.tsx
public/app/percona/backup/components/BackupInventory/BackupInventoryDetails/BackupInventoryDetails.tsx

What this PR does / why we need it: removes "test results" from Backup list, as we don't have the implementation yet
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-8008

PMM-8008: remove "test results" field

---

public/app/percona/settings/components/PlatformLogin/PlatformLogin.constants.ts
public/app/percona/settings/components/PlatformLogin/PlatformLogin.messages.ts
public/app/percona/settings/components/PlatformLogin/PlatformLogin.styles.ts
public/app/percona/settings/components/PlatformLogin/SignIn/SignIn.test.tsx
public/app/percona/settings/components/PlatformLogin/SignIn/SignIn.tsx

SAAS-508 add reset password link in SignIn

---

public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.utils.test.ts
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.utils.ts
public/app/percona/dbaas/components/DBCluster/EditDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.tsx

**What this PR does / why we need it**: Fixes request error due to request being called when the number of nodes is invalid
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7911

PMM-7911 Fixes invalid number of nodes error

---

public/app/percona/settings/Settings.tsx

What this PR does: fix breaking login / signup
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-8037

PMM-8037: move getSettings to the top

---

public/app/percona/dbaas/components/DBCluster/DBCluster.tsx
public/app/percona/dbaas/components/DBCluster/__mocks__/dbClustersStubs.ts

**What this PR does / why we need it**: Fix connection column wrong values when deleting cluster by adding a custom unique key to DB cluster rows to prevent keys getting mixed up when using index as key.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7184

PMM-7184 Fix connection column wrong values

---

public/app/core/components/Footer/Footer.tsx

What this PR does / why we need it: fix community link on sidebar
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-8095

PMM-8095: fix community link

---

public/app/percona/settings/components/PlatformLogin/SignUp/SignUp.tsx

**What this PR does / why we need it**:  To open agreements in new tab
**Which issue(s) this PR fixes**: PMM-6676
Fixes #

PMM-6676 add new tab open

---

package.json
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterBasicOptions/DBClusterBasicOptions.constants.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterBasicOptions/DBClusterBasicOptions.test.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterBasicOptions/DBClusterBasicOptions.tsx
yarn.lock

**What this PR does / why we need it**: Validates the length of the cluster name
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7755
https://github.com/Percona-Lab/pmm-submodules/pull/1783

PMM-7755 Validate cluster name length

---

pkg/api/api.go
pkg/api/index.go
public/app/core/components/sidemenu/TopSection.tsx
public/app/percona/settings/components/Advanced/Advanced.tsx

**What this PR does / why we need it**: Uncomment backup feature

PMM-8135: enable backup feature

---

public/app/percona/dbaas/components/DBCluster/DBCluster.hooks.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.types.ts
public/app/percona/dbaas/components/DBCluster/DeleteDBClusterModal/DeleteDBClusterModal.tsx
public/app/percona/dbaas/components/DBCluster/DeleteDBClusterModal/DeleteDBClusterModal.types.ts
public/app/percona/dbaas/components/DBCluster/__mocks__/DBCluster.hooks.ts

**What this PR does / why we need it**: Triggers DB Clusters table loading on delete and immediately closes the modal
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8115
https://github.com/Percona-Lab/pmm-submodules/pull/1797

PMM-8115 Trigger table loading on db cluster delete

---

pkg/api/index.go

**What this PR does / why we need it**: Fix QAN menu typo
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8021

PMM-8021 Fix QAN menu typo

---

public/app/percona/dbaas/DBaaS.messages.ts

**What this PR does / why we need it**: Change cluster name validation message
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7970

PMM-7970 Fix cluster name validation message

---

.github/workflows/ui-tests.yml
Makefile
docker-compose.yml
yarn.lock

https://github.com/percona/pmm-ui-tests/pull/30

SAAS-554 UI tests execution on PR

---

public/app/percona/settings/components/PlatformLogin/SignIn/SignIn.tsx
public/app/percona/settings/components/PlatformLogin/SignUp/SignUp.tsx
public/app/percona/shared/helpers/validators.test.tsx
public/app/percona/shared/helpers/validators.ts

https://github.com/Percona-Lab/pmm-submodules/pull/1819

PMM-6627 trim inputs

---

public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/AddDBClusterModal.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterBasicOptions/DBClusterBasicOptions.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.types.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.types.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.utils.test.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.utils.ts

**What this PR does / why we need it**: Selects initial database type and pre-selects database type if only one operator is installed
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7828
https://github.com/Percona-Lab/pmm-submodules/pull/1812

PMM-7828 Selects database type for installed operator

---

public/app/percona/dbaas/components/DBCluster/DBCluster.hooks.ts

Changes from 2.18.0

---

public/app/percona/backup/Backup.messages.ts
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.service.ts
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx

**What this PR does / why we need it**: Removes a scheduled backup
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8240

PMM-8240: remove scheduled backup

---

public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.service.ts
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx

**What this PR does / why we need it**: Toggles a scheduled backup (active / inactive)
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8241

Pmm 8241 toggle scheduled backup

---

public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx

**What this PR does / why we need it**: Copies a scheduled backup
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8243

PMM-8243: copy scheduled backup

---

public/app/features/dashboard/components/ShareModal/ShareSnapshot.tsx
public/app/features/dashboard/dashgrid/DashboardGrid.tsx
public/app/features/dashboard/state/DashboardModel.ts
public/app/features/dashboard/state/PanelModel.ts

Changes from 2.19.0

---

.github/workflows/ci.yml
.github/workflows/ui-tests.yml

**What this PR does / why we need it**: Adds step to clean yarn cache in the job to Run Unit Tests

PMM-7809 Clean yarn cache

---

Makefile

Fix yarn install

---

public/app/percona/add-instance/components/Discovery/Discovery.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.types.ts

**What this PR does / why we need it**: RDS instance discovery shouldn't start if credentials are empty
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8411

PMM-8411 Discovery starts immediately 

---

public/app/percona/backup/components/BackupInventory/BackupInventoryActions/BackupInventoryActions.tsx

**What this PR does / why we need it** Hides backup deletion for next release

backups: hide delete action

---

public/app/percona/add-instance/components/Discovery/Discovery.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.types.ts

PMM-7690 is incomplete, it has too many defects:
PMM-8411 and PMM-8441
It is also not documented.
PMM-8441

PMM-7690 revert changes from 2.20

---

.github/workflows/ui-tests.yml
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/PostgreTLSCertificate.tsx

- Adds support for TLS in PostgreSQL by adding additional fields for TLS
- Increases ui tests timeout
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7903

PMM-7888 Add TLS support for PostgreSQL

---

public/app/percona/backup/components/BackupInventory/BackupInventoryActions/BackupInventoryActions.tsx

Re-add delete action to backup inventory

Backups: unhide delete action

---

public/app/percona/backup/Backup.messages.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.messages.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.tsx

**What this PR does / why we need it**: Lets users know they are scheduling using UTC time.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8542

PMM-8542: add utc labels to scheduled backups

---

public/app/percona/settings/components/Communication/Email/Email.tsx

**What this PR does / why we need it**: Validates email on Communication settings
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7612

PMM-7612 validate email communication

---

public/app/core/components/sidemenu/TopSection.tsx

**What this PR does / why we need it**: Disables error notifications on settings requests done for the left menu. The error was not needed anyway, if it fails the menu items just don't get added to the menu (in new features we are handling this cases with insufficient access or feature disabled messages). Grafana image rendering plugin when rendering an image renders the menu and our settings request gets fired, causing an error because the way the plugin is implemented doesn't have access to our backend.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8404

PMM-8404 Fix image rendering

---

public/app/percona/backup/components/BackupInventory/BackupInventory.tsx

**What this PR does / why we need it**: Adds missing spinner to delete modal on backup list
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8549

PMM-8549: show spinner on delete modal for backup list

---

public/app/percona/add-instance/components/Discovery/Discovery.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.types.ts
public/app/percona/backup/components/BackupInventory/BackupInventoryActions/BackupInventoryActions.tsx

Changes from 2.20.0

---

public/app/app.ts

**What this PR does / why we need it**: Fixes unauthorised error on login screen. This was fixed in grafana side, reimplement the fix here while we don't pull the latest version from upstream: 
https://github.com/grafana/grafana/issues/34645
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8559

PMM-8559 Fix unauthorised error

---

public/app/percona/backup/components/AddBackupModal/AddBackupModal.tsx
public/app/percona/backup/components/BackupInventory/BackupInventory.constants.ts
public/app/percona/backup/components/Status/Status.styles.ts
public/app/percona/backup/components/Status/Status.test.tsx
public/app/percona/backup/components/Status/Status.tsx
public/app/percona/shared/components/Elements/Icons/Ellipsis.styles.ts
public/app/percona/shared/components/Elements/Icons/Ellipsis.tsx
public/app/percona/shared/components/Elements/Icons/index.tsx

**What this PR does / why we need it**: Adds a loading animation for backups and restores
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8267
https://user-images.githubusercontent.com/4190654/128165751-534ef06e-7bf1-46be-b460-50227567d02f.mov

PMM-8267: backup status loading animation

---

public/app/percona/backup/components/BackupInventory/BackupInventoryActions/BackupInventoryActions.tsx

**What this PR does / why we need it**: uncomment delete action on backup list
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8616

PMM-8616 uncomment backup delete action

---

public/app/percona/settings/Settings.types.ts
public/app/percona/settings/components/Advanced/Advanced.tsx

**What this PR does / why we need it**: Allows to use the "Check for updates" button in the settings to also disable this option
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8510

PMM-8509 Disable check for updates

---

public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.test.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.tsx
public/app/percona/dbaas/components/DBCluster/EditDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.test.tsx
public/app/percona/dbaas/components/DBCluster/EditDBClusterModal/DBClusterAdvancedOptions/DBClusterAdvancedOptions.tsx
public/app/percona/dbaas/components/DBCluster/EditDBClusterModal/EditDBClusterModal.tsx

**What this PR does / why we need it**: Fixes initial number of nodes when editing a DB cluster
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7392
https://github.com/Percona-Lab/pmm-submodules/pull/1946

PMM-7392 Fix initial number of nodes

---

public/app/percona/add-instance/components/Discovery/Discovery.constants.ts
public/app/percona/add-instance/components/Discovery/Discovery.messages.ts
public/app/percona/add-instance/components/Discovery/Discovery.service.ts
public/app/percona/add-instance/components/Discovery/Discovery.test.tsx
public/app/percona/add-instance/components/Discovery/Discovery.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.messages.ts
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.styles.ts
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.test.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.tsx
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.types.ts
public/app/percona/add-instance/components/Discovery/components/DiscoveryDocs/DiscoveryDocs.constants.ts
public/app/percona/add-instance/components/Discovery/components/DiscoveryDocs/DiscoveryDocs.messages.ts
public/app/percona/add-instance/components/Discovery/components/DiscoveryDocs/DiscoveryDocs.styles.ts
public/app/percona/add-instance/components/Discovery/components/DiscoveryDocs/DiscoveryDocs.test.tsx
public/app/percona/add-instance/components/Discovery/components/DiscoveryDocs/DiscoveryDocs.tsx

- Discover RDS instances automatically at the start, if error occurs hide it
- Allow discovery without credentials, show proper error about IAM roles if it fails
- Add documentation section with new link to configure IAM roles
- Fix responsiveness of discovery RDS instances page
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7690

PMM-7690 Discovery based on IAM roles

---

docker-compose.yml

fix failing UI test

---

public/app/percona/dbaas/DBaaS.messages.tsx
public/app/percona/dbaas/DBaaS.tsx
public/app/percona/dbaas/components/Kubernetes/Kubernetes.constants.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.hooks.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.service.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.types.ts
public/app/percona/dbaas/components/Kubernetes/KubernetesInventory.test.tsx
public/app/percona/dbaas/components/Kubernetes/KubernetesInventory.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/KubernetesOperatorStatus/KubernetesOperatorStatus.test.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/KubernetesOperatorStatus/KubernetesOperatorStatus.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/KubernetesOperatorStatus/KubernetesOperatorStatus.types.ts
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/KubernetesOperatorStatus/UpdateOperatorModal/UpdateOperatorModal.styles.ts
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/KubernetesOperatorStatus/UpdateOperatorModal/UpdateOperatorModal.test.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/KubernetesOperatorStatus/UpdateOperatorModal/UpdateOperatorModal.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/KubernetesOperatorStatus/UpdateOperatorModal/UpdateOperatorModal.types.ts
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/OperatorStatusItem.test.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/OperatorStatusItem.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/OperatorStatusItem.types.ts
public/app/percona/dbaas/components/Kubernetes/__mocks__/Kubernetes.hooks.ts
public/app/percona/dbaas/components/Kubernetes/__mocks__/Kubernetes.service.ts
public/app/percona/dbaas/components/Kubernetes/__mocks__/kubernetesStubs.ts

**What this PR does / why we need it**: Adds feature to update operator when new version is available
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8264

PMM-8264 Update operators

---

public/app/percona/backup/components/Status/Status.tsx

**What this PR does / why we need it**: adds `data-qa` to status pending component.

Status: add data-qa to pending component

---

public/app/percona/settings/Settings.constants.ts
public/app/percona/settings/Settings.messages.ts
public/app/percona/settings/Settings.styles.ts
public/app/percona/settings/components/AlertManager/AlertManager.styles.ts
public/app/percona/settings/components/AlertManager/AlertManager.tsx

**What this PR does / why we need it**: Adds a warning to Alertmanager settings
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8669

PMM-8669 add warning to AM settings

---

public/app/percona/backup/components/AddBackupModal/AddBackupModal.utils.test.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.utils.ts

**What this PR does / why we need it**: When clicking the "Create backup" action from Backup inventory, add defaults to retry mode and time.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8837

PMM-8837: default retries for on-demand backups

---

public/app/percona/backup/Backup.messages.ts
public/app/percona/backup/Backup.types.ts
public/app/percona/backup/Backup.utils.test.ts
public/app/percona/backup/Backup.utils.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.messages.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.test.tsx
public/app/percona/backup/components/AddBackupModal/AddBackupModal.tsx
public/app/percona/backup/components/AddBackupModal/AddBackupModal.types.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.utils.test.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.utils.ts
public/app/percona/backup/components/AddBackupModal/__mocks__/AddBackupModal.service.ts
public/app/percona/backup/components/BackupInventory/BackupInventory.service.ts
public/app/percona/backup/components/BackupInventory/BackupInventory.tsx
public/app/percona/backup/components/BackupInventory/BackupInventory.types.ts
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.test.tsx
public/app/percona/backup/components/BackupInventory/__mocks__/BackupInventory.service.ts
public/app/percona/backup/components/RestoreHistory/RestoreHistory.types.ts
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.service.ts
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.types.ts
public/app/percona/backup/components/ScheduledBackups/__mocks__/ScheduledBackups.service.ts

**What this PR does / why we need it**: Adds PITR backups for MongoDB
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8271

PMM-8271 PITR backups for Mongo

---

public/app/percona/dbaas/DBaaS.messages.tsx
public/app/percona/dbaas/components/DBCluster/ColumnRenderers/ColumnRenderers.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.test.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.types.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.utils.test.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.utils.tsx
public/app/percona/dbaas/components/DBCluster/DBClusterActions/DBClusterActions.test.tsx
public/app/percona/dbaas/components/DBCluster/DBClusterActions/DBClusterActions.tsx
public/app/percona/dbaas/components/DBCluster/DBClusterActions/DBClusterActions.types.ts
public/app/percona/dbaas/components/DBCluster/DBClusterStatus/DBClusterStatus.constants.ts
public/app/percona/dbaas/components/DBCluster/EditDBClusterModal/EditDBClusterModal.tsx
public/app/percona/dbaas/components/DBCluster/PSMDB.service.ts
public/app/percona/dbaas/components/DBCluster/UpdateDBClusterModal/UpdateDBClusterModal.messages.tsx
public/app/percona/dbaas/components/DBCluster/UpdateDBClusterModal/UpdateDBClusterModal.styles.ts
public/app/percona/dbaas/components/DBCluster/UpdateDBClusterModal/UpdateDBClusterModal.test.tsx
public/app/percona/dbaas/components/DBCluster/UpdateDBClusterModal/UpdateDBClusterModal.tsx
public/app/percona/dbaas/components/DBCluster/UpdateDBClusterModal/UpdateDBClusterModal.types.ts
public/app/percona/dbaas/components/DBCluster/XtraDB.service.ts
public/app/percona/dbaas/components/DBCluster/__mocks__/PSMDB.service.ts
public/app/percona/dbaas/components/DBCluster/__mocks__/XtraDB.service.ts
public/app/percona/dbaas/components/DBCluster/__mocks__/dbClustersStubs.ts

**What this PR does / why we need it**: 
Recreation of https://github.com/percona-platform/grafana/pull/228

PMM-8167 DB cluster update 

---

public/app/percona/settings/components/Communication/Communication.messages.ts
public/app/percona/settings/components/Communication/Email/Email.utils.ts

**What this PR does / why we need it**: Improves tooltip for SMTP smarthost and adds default value to "hello"
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8122

PMM-8122: Improve SMTP settings description

---

public/app/percona/backup/components/AddBackupModal/AddBackupModal.messages.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.styles.ts
public/app/percona/backup/components/AddBackupModal/AddBackupModal.tsx
public/app/percona/backup/components/AddBackupModal/AddBackupModal.types.ts
public/app/percona/backup/components/BackupErrorSection/BackupErrorSection.messages.ts
public/app/percona/backup/components/BackupErrorSection/BackupErrorSection.styles.ts
public/app/percona/backup/components/BackupErrorSection/BackupErrorSection.tsx
public/app/percona/backup/components/BackupErrorSection/BackupErrorSection.types.ts
public/app/percona/backup/components/BackupInventory/BackupInventory.tsx
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.tsx
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.types.ts
public/app/percona/shared/core/types.ts
public/app/percona/shared/helpers/api.test.ts
public/app/percona/shared/helpers/api.ts

**What this PR does / why we need it**: Adds a verbose error and links to docs in case a backup/restore fails
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8803

PMM-8803: friendly backup error

---

pkg/api/index.go

This PR adds the missing menu InnoDB Details item in left menu
https://jira.percona.com/browse/PMM-8387

PMM-8387-add-InnoDB-Details-dashboard-to-the-left-menu

---

public/app/percona/settings/components/MetricsResolution/MetricsResolution.styles.ts

[Jira ticket](https://jira.percona.com/browse/PMM-8547)

PMM-8547: fix error message-text wrapping

---

package.json
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.messages.ts
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx
public/app/percona/shared/components/Form/MultiSelectField/MultiSelectField.test.tsx
public/app/percona/shared/components/Form/MultiSelectField/MultiSelectField.tsx
public/app/percona/shared/components/Form/SelectField/SelectField.test.tsx
public/app/percona/shared/components/Form/SelectField/SelectField.tsx
yarn.lock

**What this PR does / why we need it**: Uses new tooltip feature for form fields
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8674

PMM-8674: add label tooltips from platform-core

---

public/app/percona/backup/components/ScheduledBackups/ScheduledBackupsActions/ScheduledBackupsActions.styles.ts
public/app/percona/backup/components/ScheduledBackups/ScheduledBackupsActions/ScheduledBackupsActions.tsx
public/app/percona/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplateActions/AlertRuleTemplateActions.styles.ts
public/app/percona/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplateActions/AlertRuleTemplateActions.tsx
public/app/percona/integrated-alerting/components/AlertRules/AlertRules.test.tsx
public/app/percona/integrated-alerting/components/AlertRules/AlertRules.tsx
public/app/percona/integrated-alerting/components/AlertRules/AlertRulesActions/AlertRulesActions.styles.ts
public/app/percona/integrated-alerting/components/AlertRules/AlertRulesActions/AlertRulesActions.tsx
public/app/percona/integrated-alerting/components/Alerts/AlertsActions/AlertsActions.tsx
public/app/percona/integrated-alerting/components/NotificationChannel/NotificationChannelActions/NotificationChannelActions.styles.ts
public/app/percona/integrated-alerting/components/NotificationChannel/NotificationChannelActions/NotificationChannelActions.tsx
public/app/percona/shared/components/Elements/ExpandableCell/ExpandableCell.tsx

**What this PR does / why we need it**: 
Adds improvements to IA's UI, namely:
- Bigger 'delete' icon;
- Bigger up/down arrow icons;
- Tooltips for actions;
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-7527

PMM-7527 UI improvs to IA

---

public/app/percona/dbaas/components/DBCluster/DBClusterStatus/DBClusterStatus.test.tsx
public/app/percona/dbaas/components/DBCluster/DBClusterStatus/DBClusterStatus.tsx

**What this PR does / why we need it**: Shows db cluster message logs when the cluster is changing and not only when the cluster has a failing status. This is required to support PXC 1.9.0 because of the way it treats errors.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8731

PMM-8731 Show db cluster message when changing

---

public/app/percona/dbaas/DBaaS.tsx
public/app/percona/dbaas/components/Kubernetes/Kubernetes.hooks.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.types.ts
public/app/percona/shared/components/Elements/FeatureLoader/FeatureLoader.test.tsx
public/app/percona/shared/components/Elements/FeatureLoader/FeatureLoader.tsx
public/app/percona/shared/components/Elements/FeatureLoader/FeatureLoader.types.ts

**What this PR does / why we need it**: Wait until we get the settings to call DBaaS API. Adds function to `FeatureLoader` to retrieve the settings so there's no need to duplicate code outside and duplicate call to the settings.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8461

PMM-8461 Wait for settings before calling DBaaS API

---

public/app/percona/settings/Settings.types.ts
public/app/percona/settings/__mocks__/Settings.service.ts
public/app/percona/settings/components/Communication/Email/Email.test.tsx
public/app/percona/settings/components/Communication/Email/Email.tsx
public/app/percona/settings/components/Communication/Email/Email.types.ts
public/app/percona/settings/components/Communication/Email/Email.utils.test.tsx
public/app/percona/settings/components/Communication/Email/Email.utils.ts

**What this PR does / why we need it**: Adds a "Require TLS" checkbox to SMTP settings
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9117

PMM-9117: add "require TLS"

---

public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/MongodbTLSCertificate.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/MysqlTLSCertificate.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/PostgreTLSCertificate.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.messages.ts

It might not be clear to user which file goes to which form
https://jira.percona.com/browse/PMM-8282

PMM-8282-add-tooltips-to-tls-options: add tooltips

---

public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterBasicOptions/DBClusterBasicOptions.constants.tsx
public/app/percona/dbaas/components/DBCluster/AddDBClusterModal/DBClusterBasicOptions/DBClusterBasicOptions.types.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.constants.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.hooks.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.service.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.types.ts
public/app/percona/dbaas/components/DBCluster/DBCluster.utils.test.tsx
public/app/percona/dbaas/components/DBCluster/DBCluster.utils.tsx
public/app/percona/dbaas/components/DBCluster/PSMDB.service.ts
public/app/percona/dbaas/components/DBCluster/XtraDB.service.ts
public/app/percona/dbaas/components/DBCluster/__mocks__/dbClustersStubs.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.constants.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.types.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.utils.test.ts
public/app/percona/dbaas/components/Kubernetes/KubernetesInventory.tsx
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersions.hooks.test.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersionsModal.messages.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/ManageComponentsVersionsModal.types.ts
public/app/percona/dbaas/components/Kubernetes/ManageComponentsVersionsModal/__mocks__/componentsVersionsStubs.ts
public/app/percona/dbaas/components/Kubernetes/__mocks__/kubernetesStubs.ts

**What this PR does / why we need it**: Refactor DBaaS to use the new API:
- Single list request for every database type
- Delete and restart requests require database type
- Replace xtradb with pxc
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8514

PMM-8514 Refactor DBaaS API

---

public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.service.tsx
public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.types.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/validators.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/validators.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.messages.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.test.tsx

(https://jira.percona.com/browse/PMM-9193)

PMM-9193-add-collection-metrics-fields-to-mongo: add fields

---

public/app/percona/dbaas/components/Kubernetes/Kubernetes.hooks.ts

**What this PR does / why we need it**: Adds missing dependency
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9203

PMM-9203 DB Clusters not listing

---

public/app/percona/settings/Settings.tsx

**What this PR does / why we need it**: Adds a "tech preview" disclaimer to Settings > Portal
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9296
Using portal to achieve this, as `TechPreview` was done to be used within the `PageWrapper`, but we don't want the disclaimer in the whole Settings page, but only in the `Portal` tab.

PMM-9296 use portal to add TechPreview to platform

---

public/app/percona/integrated-alerting/components/Alerts/AlertsActions/AlertsActions.tsx

**What this PR does / why we need it**: Changes title on alerts' toggle
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9181

PMM-9181 change toggle text

---

public/app/percona/settings/components/Platform/Connected/Connected.messages.ts
public/app/percona/settings/components/Platform/Connected/Connected.test.tsx
public/app/percona/settings/components/Platform/Connected/Connected.tsx
public/app/percona/settings/components/Platform/Platform.service.ts
public/app/percona/settings/components/Platform/Platform.tsx
public/app/percona/settings/components/Platform/types.ts

**What this PR does / why we need it**: Adds button to disconnect from Portal
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9059

PMM-9059 disconnect portal

---

public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.messages.ts
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.styles.ts
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.test.tsx
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AdvancedRuleSection/AdvancedRuleSection.styles.ts
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AdvancedRuleSection/AdvancedRuleSection.tsx
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AdvancedRuleSection/AdvancedRuleSection.types.ts

**What this PR does / why we need it**: Removes template expression and alert sample from rule modal
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9180

PMM-9180 alert rule: expression and sample alert are collapsible 

---

public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx

**What this PR does / why we need it**: When editing a rule, check its own expression first before checking the template itself. This way, changing the template's expression won't affect the expression shown on the modal
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9347

PMM-9347 check first rule expression

---

public/app/percona/settings/components/Platform/Connect/Connect.tsx
public/app/percona/settings/components/Platform/Platform.constants.ts

**What this PR does / why we need it**: Adds a small delay between connecting to Portal and retrieving settings from API
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9255

PMM-9255 add delay after connecting to portal

---

public/app/percona/dbaas/components/Kubernetes/AddKubernetesModal/AddKubernetesModal.constants.ts
public/app/percona/dbaas/components/Kubernetes/AddKubernetesModal/AddKubernetesModal.messages.ts
public/app/percona/dbaas/components/Kubernetes/AddKubernetesModal/AddKubernetesModal.styles.ts
public/app/percona/dbaas/components/Kubernetes/AddKubernetesModal/AddKubernetesModal.test.tsx
public/app/percona/dbaas/components/Kubernetes/AddKubernetesModal/AddKubernetesModal.tsx
public/app/percona/dbaas/components/Kubernetes/AddKubernetesModal/AddKubernetesModal.types.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.service.ts
public/app/percona/dbaas/components/Kubernetes/Kubernetes.types.ts
public/app/percona/dbaas/components/Kubernetes/KubernetesInventory.tsx

**What this PR does / why we need it**: Adds AWS access key ID and secret access key to Kubernetes register modal so users that are using EKS and this values are not present in kubeconfig can fill them. If those users don't fill these fields an error is thrown since the cluster register fails.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9336

PMM-9336 Add AWS access key ID and secret access key

---

public/app/features/api-keys/ApiKeys.messages.ts
public/app/features/api-keys/ApiKeys.styles.ts
public/app/features/api-keys/ApiKeysPage.tsx
public/app/percona/shared/components/Elements/WarningBlock/WarningBlock.tsx
public/app/percona/shared/components/Elements/WarningBlock/WarningBlock.types.ts

**What this PR does / why we need it**: Adds a warning about deletion of API keys
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8045

PMM-8045 Delete API keys warning

---

package.json
public/app/percona/integrated-alerting/components/AlertRules/AddAlertRuleModal/AddAlertRuleModal.tsx
public/app/percona/integrated-alerting/components/Alerts/AlertDetails/AlertDetails.messages.ts
public/app/percona/integrated-alerting/components/Alerts/AlertDetails/AlertDetails.styles.ts
public/app/percona/integrated-alerting/components/Alerts/AlertDetails/AlertDetails.tsx
public/app/percona/integrated-alerting/components/Alerts/AlertDetails/AlertDetails.types.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.constants.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.styles.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.tsx
public/app/percona/integrated-alerting/components/Alerts/Alerts.types.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.utils.test.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.utils.ts
yarn.lock

**What this PR does / why we need it**: Split labels into two groups: primary and secondary, to save space. The secondary ones are shown in the detailed table row.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9183

PMM-9183: reorganize alert labels

---

public/app/percona/integrated-alerting/IntegratedAlerting.messages.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.styles.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.tsx
public/app/percona/integrated-alerting/components/Alerts/Alerts.types.ts
public/app/percona/integrated-alerting/components/Alerts/AlertsActions/AlertsActions.test.tsx
public/app/percona/integrated-alerting/components/Alerts/AlertsActions/AlertsActions.tsx

**What this PR does / why we need it**: Adds buttons to silence / unsilence all alerts at once
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9369

PMM-9369: (un)silence all alerts

---

public/app/percona/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/AddNotificationChannelModal.messages.ts
public/app/percona/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/AddNotificationChannelModal.tsx
public/app/percona/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/AddNotificationChannelModal.utils.ts
public/app/percona/integrated-alerting/components/NotificationChannel/AddNotificationChannelModal/WebHookFields/WebHookFields.tsx
public/app/percona/integrated-alerting/components/NotificationChannel/NotificationChannel.types.ts
public/app/percona/integrated-alerting/components/NotificationChannel/NotificationChannel.utils.ts

**What this PR does / why we need it**: use collapsible section for TLS settings instead of using a "Use TLS" checkbox, which was misleading
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9339

PMM-9339 make collapsible section for TLS

---

public/app/percona/settings/components/Platform/Platform.constants.ts

**What this PR does / why we need it**: Increase timeout after connection to Portal
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9603
Fixes #

PMM-9603 increase connect timeout

---

public/app/features/dashboard/components/ShareModal/ShareModal.tsx
public/sass/components/_modals.scss

**What this PR does / why we need it**: Fix ShareModal styles
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9663

PMM-9663 Fix ShareModal styles

---

public/app/percona/settings/Settings.tsx

**What this PR does / why we need it**: Fixes tech preview message not showing sometimes by using a callback ref
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9692

PMM-9692 Fix tech preview message

---

pkg/api/percona_api.go
pkg/api/system.go
public/app/percona/settings/components/Platform/Connect/Connect.tsx
public/app/percona/settings/components/Platform/Connected/Connected.tsx
public/app/percona/shared/components/PerconaBootstrapper/PerconaBootstrapper.tsx
public/app/percona/shared/core/reducers.ts
scripts/webpack/webpack.dev.js
scripts/webpack/webpack.hot.js
scripts/webpack/webpack.prod.js

**What this PR does / why we need it**: Create an endpoint on Grafana's backend to read and retrieve env var `PERCONA_SAAS_HOST `. This is then used to save the SAAS host on the store (i.e. dev or prod).
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9795

PMM-9795 get saas host

---

pkg/api/percona_api.go
pkg/api/system.go
public/app/percona/settings/components/Platform/Connect/Connect.tsx
public/app/percona/settings/components/Platform/Connected/Connected.tsx
public/app/percona/shared/components/PerconaBootstrapper/PerconaBootstrapper.tsx
public/app/percona/shared/core/reducers.ts
scripts/webpack/webpack.dev.js
scripts/webpack/webpack.hot.js
scripts/webpack/webpack.prod.js

PMM-9795 get saas host (#386)

---

public/app/percona/entitlements/Entitlements.messages.ts
public/app/percona/entitlements/Entitlements.styles.ts
public/app/percona/entitlements/EntitlementsPage.tsx
public/app/percona/entitlements/components/PageContent/PageContent.test.tsx
public/app/percona/entitlements/components/PageContent/PageContent.tsx
public/app/percona/entitlements/components/PageContent/PageContent.types.ts
public/app/percona/entitlements/components/SectionContent/SectionContent.test.tsx
public/app/percona/entitlements/components/SectionContent/SectionContent.tsx

**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9493
Fixes #

PMM-9493 entitlements v2

---

public/app/percona/settings/Settings.tsx

https://jira.percona.com/browse/PMM-9842

PMM-9842-remove-technical-preview-state: remove techPreview

---

public/app/percona/settings/Settings.messages.ts
public/app/percona/settings/components/Advanced/Advanced.tsx

Change URL that leads to docs for advisors

fix: change URL for advisors

---

public/app/percona/check/components/AllChecksTab/CheckTableRow.tsx

**What this PR does / why we need it**: Changes icon meant to edit an advisor interval
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-8326

PMM-8326 change icon for advisor interval edition

---

public/app/percona/check/components/FailedChecksTab/FailedChecksTab.styles.ts
public/app/percona/check/components/ServiceChecks/ServiceChecks.styles.ts
public/app/percona/integrated-alerting/components/Alerts/AlertDetails/AlertDetails.styles.ts
public/app/percona/integrated-alerting/components/Alerts/AlertDetails/AlertDetails.tsx
public/app/percona/integrated-alerting/components/Alerts/Alerts.styles.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.tsx

**What this PR does / why we need it**: Fixes bad style on alerts/advisors for light theme
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9848

PMM-9848: fix checks hover style

---

public/app/percona/check/Check.service.ts
public/app/percona/check/components/AllChecksTab/AllChecksTab.messages.ts
public/app/percona/check/components/AllChecksTab/AllChecksTab.styles.ts
public/app/percona/check/components/AllChecksTab/AllChecksTab.test.tsx
public/app/percona/check/components/AllChecksTab/AllChecksTab.tsx
public/app/percona/check/components/AllChecksTab/CheckTableRow.test.tsx
public/app/percona/check/components/AllChecksTab/CheckTableRow.tsx
public/app/percona/check/components/FailedChecksTab/FailedChecksTab.messages.ts
public/app/percona/check/components/FailedChecksTab/FailedChecksTab.styles.ts
public/app/percona/check/components/FailedChecksTab/FailedChecksTab.test.tsx
public/app/percona/check/components/FailedChecksTab/FailedChecksTab.tsx

**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9849
Fixes #

PMM-9849 run individual checks

---

public/app/core/components/NavBar/constants.ts
public/app/core/components/NavBar/utils.ts
public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.styles.ts
public/app/percona/add-instance/components/Discovery/components/Credentials/Credentials.styles.ts
public/app/percona/add-instance/panel.styles.ts
public/app/percona/add-instance/panel.tsx
public/app/percona/check/Check.service.ts
public/app/percona/check/components/AllChecksTab/AllChecksTab.test.tsx
public/app/percona/check/components/AllChecksTab/AllChecksTab.tsx

**What this PR does / why we need it**: Fix some UI behaviours after merging new navigation system
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9955
Fixes #

PMM-9955: UI fixes

---

public/app/percona/dbaas/components/DBCluster/DBCluster.tsx

PMM-9964 move setLoading to proper place

---

public/app/features/admin/UpgradePage.tsx

**What this PR does / why we need it**: Removes info about Grafana Enterprise from upgrading page
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9908

PMM-9908 do not render enterprise info

---

public/app/percona/integrated-alerting/components/Alerts/Alerts.tsx

**What this PR does / why we need it**: Fixes pagination on Alerts page
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-10127

PMM-10127 Fix pagination on Alerts page

---

public/app/percona/dbaas/components/Kubernetes/PortalK8sFreeClusterPromotingMessage/PortalK8sFreeClusterPromotingMessage.tsx
public/app/percona/dbaas/components/PMMServerURLWarning/PMMServerUrlWarning.tsx

https://jira.percona.com/browse/PMM-10577

PMM-10577-Typo-in-PMM-Public-Address-warning: fix typos

---

public/app/percona/backup/components/AddBackupModal/AddBackupModal.tsx
public/app/percona/backup/components/AddBackupModal/AddBackupModal.utils.ts
public/app/percona/backup/components/BackupInventory/BackupInventory.service.ts
public/app/percona/backup/components/BackupInventory/BackupInventory.tsx
public/app/percona/backup/components/ChunkedLogsViewer/ChunkedLogsViewer.tsx
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.service.ts
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx
public/app/percona/backup/hooks/recurringCall.hook.ts
public/app/percona/shared/components/hooks/cancelToken.hook.ts

**What this PR does / why we need it**: Allows physical backups for MongoDB
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-10517

PMM-10517: allow physical backups

---

public/app/core/components/NavBar/NavBar.tsx
public/app/percona/shared/components/PerconaBootstrapper/PerconaBootstrapper.tsx
public/app/tour/steps.messages.ts
public/app/tour/steps.tsx

Because of the navbar change the the pmm dashboards steps needs to be updated.
Fixes PMM-10668

PMM-10668 Update onboarding tour for new navbar

---

public/app/AppWrapper.tsx
public/app/percona/shared/components/PerconaBootstrapper/PerconaBootstrapper.tsx
public/app/percona/shared/core/reducers.ts
public/app/percona/shared/core/reducers/index.ts
public/app/percona/shared/core/reducers/user.ts
public/app/percona/shared/core/reducers/user.types.ts
public/app/percona/shared/core/reducers/user.utils.ts
public/app/percona/shared/helpers/api.ts
public/app/percona/shared/services/user/User.service.ts
public/app/percona/shared/services/user/User.types.ts
public/app/tour/NextButton.tsx
public/app/tour/TourProvider.tsx
public/app/tour/constants.ts

Uses the BE flag for the product tour to keep the viewed state synced across browsers/sessions/et.c
Fixes PMM-10667
New ticket for https://github.com/percona-platform/grafana/pull/492.

PMM-10667 Product Tour flag

---

public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.tsx

Fixes issue with TLS check when adding a database instance.
Fixes PMM-10985

PMM-10985 Fix tls switch when adding db instance

---

package.json
public/app/percona/inventory/Tabs/Agents.tsx
public/app/percona/inventory/Tabs/Nodes.tsx
public/app/percona/inventory/Tabs/Services.tsx
yarn.lock

On inventory page select only the currently viewed page to prevent accidental agents/nodes/services removals.
Fixes PMM-10732
[Core UI PR](https://github.com/percona-platform/core-ui/pull/90)

PMM-10732 Toggle only selection on current page

---

public/app/percona/settings/components/Platform/Platform.constants.ts
public/app/percona/settings/components/Platform/Platform.messages.ts
public/app/percona/settings/components/Platform/Platform.service.ts
public/app/percona/settings/components/Platform/Platform.tsx
public/app/percona/settings/components/Platform/types.ts

Adds a more descriptive message when the token used to connect to portal is either invalid or expired.
Fixes PMM-10908

PMM-10908 Portal token invalid message

---

public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.messages.ts
public/app/percona/backup/components/BackupInventory/RestoreBackupModal/RestoreBackupModal.tsx

PMM-11158 remove alert message

---

public/app/core/components/Footer/Footer.tsx

Remove links pointing to grafana version/version check from the footer.
PMM-11190
2.32
Before change
After change (same as 2.32)

PMM-11190 Remove grafana footer links

---

public/app/percona/shared/core/reducers/index.ts

https://jira.percona.com/browse/PMM-11210

PMM-11210-k8s-clusters-is-not-displayed

---

public/app/percona/backup/components/BackupInventory/BackupInventory.tsx
public/app/percona/backup/components/RestoreHistory/RestoreHistory.tsx
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx
public/app/percona/backup/components/StorageLocations/StorageLocations.tsx
public/app/percona/integrated-alerting/components/Table/Table.tsx
public/app/percona/integrated-alerting/components/Table/Table.types.ts

**What this PR does / why we need it**: Adds `getRowId` to prevent the table from expanding the wrong row when data is refreshed.
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-9977

PMM-9977 add getRowId to backup tables

---

public/app/percona/dbaas/components/DBaasRouting/DBaaSRouting.tsx

the message below was returned

PMM-11221-fix-dbaas-is-disabled-message: feauture loader was added

---

public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx

**What this PR does / why we need it**: To avoid confusion, hide the "Save" button for template alerts and just keep "Save and Exit"
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-10853

PMM-10853 hide save button for templated rules

---

public/app/percona/backup/Backup.utils.ts
public/app/percona/backup/components/BackupInventory/BackupInventory.test.tsx
public/app/percona/backup/components/BackupInventory/BackupInventory.tsx
public/app/percona/backup/components/RestoreHistory/RestoreHistory.tsx
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.test.tsx
public/app/percona/backup/components/ScheduledBackups/ScheduledBackups.tsx

https://jira.percona.com/browse/PMM-10924
Fixes #

PMM-10924 all backups pages should display storage type

---

public/app/percona/integrated-alerting/components/Alerts/Alerts.constants.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.messages.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.styles.ts
public/app/percona/integrated-alerting/components/Alerts/Alerts.tsx

https://jira.percona.com/browse/PMM-10773
Fixes #
Removed opacity and redirected to silences tab, not create new silence form

PMM-10773 Unsilence in Fired Alerts

---

public/app/features/alerting/unified/components/rule-editor/TemplateStep/TemplateStep.tsx

https://jira.percona.com/browse/PMM-11357
Fixes #
Field should inherit name from template only if user did not change name to custom one. If he did then it should stay same even after change of template.

PMM-11357 Inherite name from the template

---

public/app/percona/dbaas/components/DBCluster/EditDBClusterPage/DBClusterAdvancedOptions/DBClusterAdvancedOptions.test.tsx
public/app/percona/dbaas/components/DBCluster/EditDBClusterPage/DBClusterAdvancedOptions/DBClusterAdvancedOptions.tsx
public/app/percona/dbaas/components/DBCluster/EditDBClusterPage/EditDBClusterPage.test.tsx
public/app/percona/dbaas/components/Kubernetes/OperatorStatusItem/OperatorStatusItem.tsx

https://jira.percona.com/browse/PMM-11290
branch was recreated from https://github.com/percona-platform/grafana/pull/594

Pmm 11290 advanced options disable edit save

---

public/app/percona/check/Check.service.ts
public/app/percona/check/components/FailedChecksTab/Failures/Failures.tsx

https://jira.percona.com/browse/PMM-10016
Fixes #

PMM-10016 Advisors: Failed checks table rearranges

---

public/app/features/alerting/unified/components/rule-editor/AlertRuleForm.tsx

https://jira.percona.com/browse/PMM-11399
Fixes #

PMM-11399 Alerting: Empty rule name in pop up messages

---

public/app/percona/backup/components/BackupInventory/BackupInventory.service.ts

Fixes #
Fix because in BE in https://jira.percona.com/browse/PMM-11175 was renamed field.

Fix-PMM-11174-rename-field

---

public/app/percona/dbaas/components/PMMServerURLWarning/PMMServerUrlWarning.messages.ts
public/app/percona/dbaas/components/PMMServerURLWarning/PMMServerUrlWarning.tsx
public/app/percona/settings/components/Platform/Connect/Connect.styles.ts
public/app/percona/settings/components/Platform/Connect/Connect.tsx
public/app/percona/settings/components/Platform/Platform.messages.ts

**What this PR does / why we need it**: Changes the layout for the Portal connection from PMM
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-11113

PMM-11113: new Portal connection layout

---

packages/grafana-data/src/datetime/durationutil.ts

**What this PR does / why we need it**: Avoid a total app crash when the system's clock (browser) is behind the server time (PMM)
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-11001

PMM-11001 check time interval to avoid throw

---

public/app/features/admin/state/reducers.ts

**What this PR does / why we need it**: Fixed app crash when filtering users from admin page (/admin/users)
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-11636

PMM-11636 avoid null users

---

public/app/percona/dbaas/components/DBCluster/EditDBClusterPage/EditDBClusterPage.test.tsx
public/app/percona/dbaas/components/DBCluster/EditDBClusterPage/EditDBClusterPage.tsx
public/app/percona/dbaas/hooks/useKubernetesList.ts

https://jira.percona.com/browse/PMM-11296

PMM-11296-db-creation-page-loading: fix page loading error

---

public/app/percona/rbac/AccessRoles/AccessRoles.tsx
public/app/percona/settings/Settings.messages.ts

Update docs access control docs link to the correct one.
PMM-11759
Build: https://github.com/Percona-Lab/pmm-submodules/pull/3110

PMM-11759 Update access control docs links

---

public/app/percona/check/components/AllChecksTab/AllChecksTab.tsx
public/app/percona/integrated-alerting/components/Table/Filter/Filter.tsx
public/app/percona/integrated-alerting/components/Table/Filter/Filter.types.ts
public/app/percona/integrated-alerting/components/Table/Filter/Filter.utils.ts
public/app/percona/integrated-alerting/components/Table/Table.tsx
public/app/percona/integrated-alerting/components/Table/Table.types.ts
public/app/percona/shared/components/Elements/CustomCollapsableSection/CustomCollapsableSection.tsx
public/app/percona/shared/components/Elements/CustomCollapsableSection/CustomCollapsableSection.types.ts
public/app/percona/shared/helpers/getValuesFromQueryParams.ts
public/app/percona/shared/services/advisors/Advisors.utils.ts

https://jira.percona.com/browse/PMM-11786
Fixes #

PMM-11786 Fix for table filter

---

public/app/percona/check/components/CheckInfoAlert/CheckInfoAlert.tsx

Change advisors alert url to tracking url

---

DEVELOPMENT.PERCONA.md
conf/grafana.local-dev.ini
docker-compose.yml
package.json
pkg/api/dtos/index.go
pkg/api/index.go
public/views/index-template.html
scripts/webpack/webpack.dev.js
yarn.lock

[PMM-11819](https://jira.percona.com/browse/PMM-11819)
Along with livereload, this PR contains setup instructions and modifications for docker compose allowing build server within container.
FB:
- https://github.com/Percona-Lab/pmm-submodules/pull/3145

PMM-11819: webpack livereload plugin

---

packages/grafana-ui/src/types/react-table-config.d.ts
public/app/percona/check/components/AllChecksTab/AllChecksTab.tsx
public/app/percona/check/components/ServiceChecks/ServiceChecks.tsx
public/app/percona/integrated-alerting/components/Table/Table.styles.ts
public/app/percona/integrated-alerting/components/Table/Table.tsx
public/app/percona/integrated-alerting/components/Table/Table.types.ts

**What this PR does / why we need it**: Manually control whether or not a given cell should show overflown text
**Which issue(s) this PR fixes**: https://jira.percona.com/browse/PMM-12015

PMM-12015 add prop to control text overflow on tables

---

conf/defaults.ini
conf/sample.ini
docs/sources/setup-grafana/configure-security/configure-authentication/_index.md

Add and document option for enabling email lookup (#913)
* Docs: Document option for enabling email lookup
* Add the new config in the config files
* Apply suggestions from code review
Co-authored-by: Ieva <ieva.vasiljeva@grafana.com>
* Don't capitalize identity providers
* Apply suggestions from code review
Co-authored-by: Jo <joao.guerreiro@grafana.com>
* Apply suggestions from code review
Co-authored-by: Christopher Moyer <35463610+chri2547@users.noreply.github.com>
---------
Co-authored-by: Ieva <ieva.vasiljeva@grafana.com>
Co-authored-by: Jo <joao.guerreiro@grafana.com>
Co-authored-by: Christopher Moyer <35463610+chri2547@users.noreply.github.com>
(cherry picked from commit 8380bc7d6a79794cc260bf1c427e2b4e849adbf6)
**Which issue(s) this PR …

[v9.2.x] (PMM-12293) Add and document option for enabling email lookup (#918)

---

conf/defaults.ini
conf/sample.ini
docs/sources/setup-grafana/configure-security/configure-authentication/_index.md

Add and document option for enabling email lookup (#913)
* Docs: Document option for enabling email lookup
* Add the new config in the config files
* Apply suggestions from code review
* Don't capitalize identity providers
* Apply suggestions from code review
* Apply suggestions from code review
---------
(cherry picked from commit 8380bc7d6a79794cc260bf1c427e2b4e849adbf6)
Fixes #

[v9.2.x] Add and document option for enabling email lookup (#918) (#677)

---

public/app/percona/inventory/Inventory.constants.ts
public/app/percona/inventory/Inventory.messages.ts
public/app/percona/inventory/Tabs/Nodes.tsx
public/app/percona/inventory/Tabs/Services.tsx
public/app/percona/inventory/Tabs/Services/ClusterItem.tsx
public/app/percona/inventory/Tabs/Services/Clusters.tsx
public/app/percona/inventory/Tabs/Services/Clusters.type.tsx
public/app/percona/inventory/Tabs/Services/Clusters.utils.ts
public/app/percona/inventory/Tabs/Services/ServicesTable.tsx
public/app/percona/inventory/Tabs/Tabs.styles.ts
public/app/percona/shared/components/Elements/TechnicalPreview/TechnicalPreview.tsx
public/app/percona/shared/services/services/Services.types.ts

Adds a basic toggle to organize services by clusters.
PMM-12378
**Screenshots**:
Main view:
Cluster opened:
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3374

PMM-12378 Cluster view

---

public/app/percona/inventory/Tabs/Services/Clusters.utils.ts

PMM-12547 non clustered services view fix

---

public/app/percona/shared/components/Elements/Table/Table.styles.ts
public/app/percona/shared/components/Elements/Table/Table.tsx

**What this PR does / why we need it**: Updates the View of summary column to display full Summary instead of the "..." in Fired alerts.
**Which issue(s) this PR fixes**: 
Fixes # [PMM-12442](https://jira.percona.com/browse/PMM-12442)
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3375#issuecomment-1696902359

PMM-12442 show full summary on fired alerts

---

public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.tsx

Change default autodiscovery limit value to 10.
PMM-12709
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3454

PMM-12709 Set default autodiscovery limit to 10

---

public/app/percona/pmm-dump/PMMDump.messages.ts
public/app/percona/pmm-dump/SendToSupportModal.tsx

PMM-12884
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3549

PMM-12884 PMM Dump modal improvements.

---

public/app/percona/pmm-dump/PMMDump.messages.ts
public/app/percona/pmm-dump/SendToSupportModal.tsx

To merge PR https://github.com/percona/grafana/pull/712/files into v3 branch.

PMM-12884 PMM Dump modal improvements (merge into v3).

---

public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.tsx
public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.types.ts

Cherry pick from main
PMM-12952

PMM-12952 Use PG Stat Monitor by default

---

.betterer.results
public/app/features/dashboard/components/SubMenu/DashboardLinksDashboard.tsx

Fixes the pmm menu on dashboards.
Fixes PMM-13032
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3610

PMM-13032 Fix PMM menu on dashboards

---

public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.types.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.constants.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.messages.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.types.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.messages.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.test.tsx
public/app/percona/shared/helpers/validatorsForm/int32.ts

* PMM-12971 Add pg exporter connection limit
* PMM-12971 Add check for azure pg
* PMM-12971 Update test cases for pg max connections
* PMM-12971 Update pg max connection limit
* PMM-12971 Update default max connection logic
* PMM-12971 Update test cases
* PMM-12971 fix validation and rds parameter
* PMM-12971 Fix logic for RDS
Fixes #

PMM-12971 Add pg exporter connection limit (#750)

---

public/app/percona/inventory/Inventory.service.ts

PMM-13120
https://github.com/percona/pmm/pull/2996

PMM-13120 RemoveNode to UnregisterNode in inventory.

---

public/app/core/components/AppChrome/MegaMenu/MegaMenuItemText.tsx
public/app/percona/shared/helpers/navigation.ts

Adds templating variables and time range information to the dashboard links in the main menu.
PMM-13122
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3632

PMM-13122 Include variables in main menus dashboard links

---

public/app/percona/shared/helpers/navigation.ts

Fixes cases where current url wasn't a dashboard.
PMM-13180
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3648#issuecomment-2178970048

PMM-13180 Fix menu variables link generation

---

Makefile

Update workflow file to use `docker compose` instead of `docker-compose`.

PMM-7 UI tests pipeline fix

---

pkg/services/navtree/navtreeimpl/percona_navtree.go
public/app/percona/dbaas/components/DBCluster/DBClusterName/DBClusterName.constants.ts

Updates menu structure for mongo related dashboards.
PMM-13258
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3690#issuecomment-2288407904

PMM-13258 Update folder structure

---

pkg/services/navtree/navtreeimpl/percona_navtree.go

Add a left menu item and link it to the new MongoDB Router Summary dashboard
Fixes PMM-13327

PMM-13327 Add menu item for Mongo Router Summary

---

public/app/plugins/datasource/pmm-pt-summary-datasource/PTSummary.types.ts
public/app/plugins/datasource/pmm-pt-summary-datasource/PTSummaryDataSource.test.ts
public/app/plugins/datasource/pmm-pt-summary-datasource/PTSummaryDataSource.ts

Fixes handling of the BE response for summary action results.
PMM-13417
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3745

PMM-13417 Fix summary action result handling

---

.github/workflows/ui-tests.yml

Use target PR branch as base for the UI tests if available. The order is now following:
1. Base PR branch (e.q. `PMM-7-ui-tests-target-branch`)
2. Target PR branch (e.q. `v3`)
3. Main branch
UI Tests fix: https://github.com/percona/pmm-ui-tests/pull/911

PMM-7 Check target branch when checking out UI tests

---

public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/MongoDBConnectionDetails/MongoDBConnectionDetails.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/MySQLConnectionDetails/MySQLConnectionDetails.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/NodesAgents/NodesAgents.constants.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/NodesAgents/NodesAgents.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/NodesAgents/NodesAgents.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/PostgreSQLConnectionDetails/PostgreSQLConnectionDetails.test.tsx

This PR fixes following issues:
- Adds validation for node/agent fields
- Uses FinalForm to store the selected node (to allow to preselect and keep the values after unsuccessful submit)
- Preselects pmm-server node (when available)
- Fixes warnings during test execution when the NodesAgents component is inside the tree
PMM-13548
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3786

PMM-13548 Add service node selection fixes

---

public/app/percona/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.service.ts
public/app/percona/integrated-alerting/components/AlertRuleTemplate/AlertRuleTemplate.types.ts

Reloads alert rule templates from disk by default.
PMM-13542
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3783

PMM-13542 Reload templates by default

---

public/app/percona/shared/components/PerconaBootstrapper/PerconaMigrator/components/MigrationSummary.constants.ts

PMM-7 Use shortened link for service account migration docs link

---

public/app/percona/tickets/Tickets.service.ts

Uses the correct api for fetching portal tickets.
Fixes PMM-13682
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3824

PMM-13682 Tickets api

---

.github/workflows/ui-tests.yml

Update upload artifact action to v4 due to [deprecation](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) of v3.

PMM-7 Update upload artifact action to v4

---

public/app/features/datasources/components/picker/AddNewDataSourceButton.tsx
public/app/features/datasources/components/picker/DataSourceModal.test.tsx
public/app/features/datasources/components/picker/DataSourcePicker.test.tsx

Cherry pick of https://github.com/grafana/grafana/pull/90536
PMM-13546

PMM-13546 Alerting - New data source - Incorrect link

---

public/app/percona/shared/core/hooks/migrator.ts

https://perconadev.atlassian.net/browse/PMM-13717

PMM-13717: Errors appear when a user with a non-admin role logs in to PMM

---

public/app/percona/settings/Settings.service.ts
public/app/percona/shared/core/reducers/index.ts

https://perconadev.atlassian.net/browse/PMM-12881
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3859

PMM-12881: Changing PMM settings shows successful notification even when it fails

---

emails/templates/invited_to_org.mjml
emails/templates/invited_to_org.txt
emails/templates/new_user_invite.mjml
emails/templates/new_user_invite.txt
emails/templates/ng_alert_notification.mjml
emails/templates/partials/alerting/contact_us.mjml
emails/templates/partials/alerting/contact_us_firing.mjml
emails/templates/partials/layout/footer.mjml
emails/templates/partials/layout/header.mjml
emails/templates/reset_password.mjml
emails/templates/reset_password.txt
emails/templates/signup_started.mjml
emails/templates/signup_started.txt
emails/templates/welcome_on_signup.mjml
emails/templates/welcome_on_signup.txt
public/emails/invited_to_org.html
public/emails/invited_to_org.txt
public/emails/new_user_invite.html
public/emails/new_user_invite.txt
public/emails/ng_alert_notification.html
public/emails/reset_password.html
public/emails/reset_password.txt
public/emails/signup_started.html
public/emails/signup_started.txt
public/emails/verify_email.html
public/emails/welcome_on_signup.html
public/emails/welcome_on_signup.txt

FB: https://github.com/Percona-Lab/pmm-submodules/pull/3835

PMM-13676: PMM Branded Logo in PMM generated Emails

---

.github/workflows/ci.yml
.github/workflows/ui-tests.yml

Updates node version used in pipelines to version 22.
Fixes PMM-13549

PMM-13549 Use node 22 for pipelines

---

public/app/percona/inventory/Tabs/Services/ServicesTable.tsx

Prevents the reset of the page index when services are fetched.
PMM-13909
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3890

PMM-13909 Prevent resetting the page index on services table

---

public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.tsx

Add option to skip connection check and/or skip tls verification to external services and HA Proxy.
PMM-13887
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3902

PMM-13887 Add option to skip tls verification

---

public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.service.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.service.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/FormParts.messages.ts
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/MySQLConnectionDetails/MySQLConnectionDetails.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/MySQLConnectionDetails/MySQLConnectionDetails.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/PostgreSQLConnectionDetails/PostgreSQLConnectionDetails.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/FormParts/PostgreSQLConnectionDetails/PostgreSQLConnectionDetails.tsx

https://perconadev.atlassian.net/browse/PMM-14257
BE: https://github.com/percona/pmm/pull/4299
FB: https://github.com/Percona-Lab/pmm-submodules/pull/4002

PMM-14257 add instance id field for add service step 2

---

public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.service.test.tsx
public/app/percona/add-instance/components/AddRemoteInstance/AddRemoteInstance.service.tsx

Send node_name at root level only for RDS
PMM-14289
FB: https://github.com/Percona-Lab/pmm-submodules/pull/4024

PMM-14289 Fix node_name payload
